name: Deploy to AKS

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client_id: ${{ secrets.b6403821-d790-483e-b2c4-0768b83d73d5 }}
          client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant_id: ${{ secrets.aaf01420-8f32-49e5-bcef-795340c1f96a }}

      - name: Get AKS credentials
        uses: azure/aks-get-credentials@v1
        with:
          resource_group: ${{ secrets.Banquito-Prod }}
          cluster_name: ${{ secrets.Banquito-Prod-AKS }}

      - name: Deploy to AKS
        run: kubectl apply -f ./kubernetes/manifest.yaml